### ISSUE TITLE
CM_ProcessTest::testForkAndWaitForChildren fails

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/CM#1285] opened 2014-06-12 09:39 UTC
I got this failure a few times already.

```
1) CM_ProcessTest::testForkAndWaitForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Child 1 terminated after 100 ms.
-Child 2 terminated after 200 ms.
-Parent listening to children...
-Child 3 terminated after 300 ms.
 Child 4 terminated after 400 ms.
 All children terminated.
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/27387842

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
-Child 4 heard by parent...
+Child 3 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
 ```
https://travis-ci.org/cargomedia/CM/jobs/57613849

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
+Child 3 heard by parent...
 Child 4 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57445603

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Child 2 terminated after 175 ms.
+Child 3 terminated after 275 ms.
 Parent listening for children...
 Parent stops listening to children...
 Child 1 heard by parent...
 Child 2 heard by parent...
 Parent waiting for 100 ms...
-Child 3 terminated after 275 ms.
@@ @@
 Parent stops listening to children...
-Child 4 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57032254

```
1) CM_ProcessTest::testForkAndListenForChildren
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 Parent stops listening to children...
-Child 3 heard by parent...
 Parent waiting for 100 ms...
 Child 4 terminated after 375 ms.
 Parent listening for children...
 Parent stops listening to children...
-Child 4 heard by parent...
+Child 3 heard by parent...
 Parent waiting for 100 ms...
 Parent listening for children...
 Parent stops listening to children...
+Child 4 heard by parent...
 Parent terminated.
```
https://travis-ci.org/cargomedia/CM/jobs/57027415

**Comment by fauvel** [comment] 2015-03-17 12:33
Might be solved by #1691 if it was related to database connections shared across forks...

**Comment by njam** [comment] 2015-03-18 13:01
Still fails on recent builds:
https://travis-ci.org/cargomedia/CM/jobs/54859604
https://travis-ci.org/cargomedia/CM/jobs/54859605

**Comment by tomaszdurka** [comment] 2015-04-07 16:08
@fauvel any news on this?

**Comment by fauvel** [comment] 2015-04-08 07:46
Giving up – feel free to take over!

**Comment by njam** [comment] 2015-04-08 09:13
Added some more cases to the description

**Comment by njam** [comment] 2015-04-14 08:41
I tried to reproduce locally, ran the tests hundreds of times and it never failed.
My guess is that it's related to travis' filesystem (I had problems with it before).
Could we use a different mechanism?

**Comment by fauvel** [comment] 2015-04-14 08:52
Maybe use Memcache instead?

**Comment by njam** [comment] 2015-04-14 09:40
I will draft something

**Comment by njam** [comment] 2015-04-21 06:29
Possible fixes merged as of: 2015-04-21

**Comment by njam** [comment] 2015-04-29 13:48
Possible fixes merged as of: 2015-04-27

**Comment by njam** [comment] 2015-05-22 14:20
Seems to be solved.
Thanks @tomaszdurka !

**Closed by njam** 2015-05-22 14:20 UTC
Labels: bug, waiting
